### ISSUE TITLE
MethodError: no method matching describe_log_streams

### ISSUE THREAD

**Issue by Octogonapus** [invenia/CloudWatchLogs.jl#48]
I encountered this crash:

```julia
Unhandled Task ERROR: MethodError: no method matching describe_log_streams(::String, ::Dict{String, Any}; aws_config=AWSConfig((<redacted>, <redacted>, <redacted>), "us-east-2", "json", 3))
Stacktrace:
  [1] describe_log_streams(config::AWSConfig, log_group_name::String, params::Dict{String, Any})
    @ CloudWatchLogs ~/.julia/packages/CloudWatchLogs/eMIGi/src/stream.jl:137
  [2] macro expansion
    @ ~/.julia/packages/Mocking/HMh91/src/mock.jl:26 [inlined]
  [3] (::CloudWatchLogs.var"#12#15"{AWSConfig, String, String})()
    @ CloudWatchLogs ~/.julia/packages/CloudWatchLogs/eMIGi/src/stream.jl:153
  [4] (::Base.var"#88#90"{Base.var"#88#89#91"{ExponentialBackOff, typeof(CloudWatchLogs.aws_retry_cond), CloudWatchLogs.var"#12#15"{AWSConfig, String, String}}})(; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./error.jl:296
  [5] #88
    @ ./error.jl:291 [inlined]
  [6] aws_retry
    @ ~/.julia/packages/CloudWatchLogs/eMIGi/src/stream.jl:15 [inlined]
  [7] new_sequence_token(config::AWSConfig, log_group::String, log_stream::String)
    @ CloudWatchLogs ~/.julia/packages/CloudWatchLogs/eMIGi/src/stream.jl:152
  [8] new_sequence_token
    @ ~/.julia/packages/CloudWatchLogs/eMIGi/src/stream.jl:131 [inlined]
  [9] update_sequence_token!
    @ ~/.julia/packages/CloudWatchLogs/eMIGi/src/stream.jl:195 [inlined]
 [10] CloudWatchLogStream
    @ ~/.julia/packages/CloudWatchLogs/eMIGi/src/stream.jl:38 [inlined]
```

It looks to be caused by this commit https://github.com/JuliaCloud/AWS.jl/commit/b8086407368c27dc21500f5a55f66a267b7d2619
Take a look at the prior state of this line https://github.com/JuliaCloud/AWS.jl/blame/7b09ec01ab2a06471ce7a0101535c60472659634/src/services/cloudwatch_logs.jl#L775

Current: `function describe_log_streams(; aws_config::AbstractAWSConfig=global_aws_config())`
Previous: `function describe_log_streams(
    logGroupName; aws_config::AbstractAWSConfig=global_aws_config()
)`

CloudWatchLogs.jl version v2.1.0
AWS.jl version v1.84.1
Julia v1.8.5

**Comment by Octogonapus** [comment]
cc @mattBrzezinski in case you weren't aware of breaking changes to AWS.jl

**Comment by mattBrzezinski** [comment]
> cc @mattBrzezinski in case you weren't aware of breaking changes to AWS.jl

Ugh.. I see what happened here. AWS has changed how to make the `describe_log_stream` requests where you provide either `logGroupIdentifier` OR `logGroupName`, but not both. Previously it defaulted to `logGroupName` being the required parameter.

Old code:

> req = describe_log_streams("my-log-group")

New code:

> req = describe_log_streams(Dict("logGroupName" => "my-log-group"))

The problem though is this function, and any others are available in their specific service modules which we get only after running `@service CloudWatchLogs`. It's not super obvious to me right now how we can inject these properly? Maybe we do something like,

```julia
macro service
    # Include services/service-name
    # Include compatibility/service-name
end
```

In the mean time to fix this you can...

1) Cap the version of `AWS.jl` in your `Project.toml`
2) Update all your code to this new version
3) Make a PR to lock `AWS.jl` to the last non-breaking version and then cap this package
